---
# Fixtures needed for puppetlabs_spec_helper
fixtures:
  forge_modules:
    apache: 'puppetlabs/apache'
    stdlib: 'puppetlabs/stdlib'
    ruby:   'puppetlabs/ruby'
  symlinks:
    apachelogcompressor: "#{source_dir}"
